### ISSUE TITLE
Kan channel

### ISSUE THREAD

**Issue by sela** [quartern/iltv#134]
That channel got another feed on their App that got all the services with subtitles. I wonder if you can add it?

**Comment by denisz1** [comment]
@sela Does the app work for you? It stopped working completely for me today.

**Comment by quartern** [comment]
At the moment my app is defunt but available for side load (see https://quartern.github.io/iltv/index_en.html)

As a "fluke" I have the subtitle version as the primary Kan11 feed and only if that stream fails it rolls into the non-subs stream, but i may make two menu options instead (or let users cycle thru multiple streams - thats more work tho :( )

I never check Issues here, only on Twitter (but I think your'e already in my group chat)
