### ISSUE TITLE
App no longer works

### ISSUE THREAD

**Issue by denisz1** [quartern/iltv#149]
Hi @quartern, as of today [Roku disabled](https://blog.roku.com/developer/beta-channels) "private channels", so the app is no longer available! :rage:

Apparently it is possible to convert to a public channel. Do you plan to do this?

This roku app has been very useful for a long time, many thanks to you!

**Comment by denisz1** [comment]
Hi everyone, author said [on twitter](https://twitter.com/quartern_roku/status/1496822387760902149)

> I have not gotten around to fix and publish a replacement app.  you should follow me and I will announce if one day I ever get to it.  In the meantime search the app store there is one app there that gives you most of the same channels

I tried them all (I think) but none is even close to this one - this one is amazing.

Does anyone know which one he is referring to?

**Comment by quartern** [comment]
> Hi everyone, author said [on twitter](https://twitter.com/quartern_roku/status/1496822387760902149)
> 
> > I have not gotten around to fix and publish a replacement app.  you should follow me and I will announce if one day I ever get to it.  In the meantime search the app store there is one app there that gives you most of the same channels
> 
> I tried them all (I think) but none is even close to this one - this one is amazing.
> 
> Does anyone know which one he is referring to?

Yeah - you should just seek out assistance from me on Twitter - I only saw this by chance 
On twitter you should follow me (and if your profile does not look suspect) I will follow you back and then add you to a user chat group where other users can help.

The other app I was referring to (which was visually much more appealing than mine) was recently discontinued (for reasons unknown)

If you want I made my defunct app available for sideload file:///home/qn/Projects/iltv-web/index_en.html  but for any updates don't expect to see me here - being in my group chat on twitter is your best bet
